version: '3.5'

services: 
  zookeeper:
    container_name: zookeeper
    image: debezium/zookeeper:${DEBEZIUM_VERSION:-1.5}
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  
  kafka:
    container_name: kafka
    image: debezium/kafka:${DEBEZIUM_VERSION:-1.5}
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181

  elastic:
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTIC_VERSION:-7.14.0}
    ports:
     - 9200:9200
    environment:
     - http.host=0.0.0.0
     - transport.host=127.0.0.1
     - xpack.security.enabled=false

  mysql:
    container_name: mysql
    image: mysql:${MYSQL_VERSION:-8.0.26}
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=root
     - MYSQL_USER=user
     - MYSQL_PASSWORD=password 

  connect:
    container_name: connect
    image: debezium/connect-jdbc-es:${DEBEZIUM_VERSION:-1.5}
    build:
      context: docker/connect
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - kafka
     - mysql
     - elastic
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
     - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${ELASTIC_VERSION:-7.14.0}
    ports:
     - 5601:5601
    links:
     - elastic
    environment:
     - ELASTICSEARCH_HOSTS=http://elastic:9200
